# Generated by Django 4.0.10 on 2023-03-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_customuser_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='CutomUser',
        ),
    ]
